const SortUrl = {
  CheckUser: 'api/check-user',
  UserLogin: 'api/login',
  BusinessLogin: 'api/Bussiness-login',
  Register: 'api/register',
  Get_categories: 'api/get-categories',
  ForgotPassword: 'api/forgot-password',
  VarifyOTP: 'api/confirm-otp',
  ResetPassword: 'api/reset-password',
  HomeData: 'api/get-home-data',
  AllServices: 'api/all-doctor-list',
  AllCards: 'api/get-cards',
  SetDoctorAccount: 'api/set-doctor-account',
  searchDoctor: 'api/get-doctors',
  DoctorDetail: 'api/doctor-detail',
  DoctorFeedbacks: 'api/doctor-feedbacks',
  AddReview: 'api/add-review',
  Follow: 'api/follow',
  card: 'api/add-card',
  Notification: 'api/get-notification',
  Profile: 'api/get-profile',
  // Business:"api/add-business",
  Notification: 'api/set-notification',
  UpdateDoctorAccount: 'api/update-doctor-account',
  UpdateDoctorProfile: 'api/update-doctor-profile',
  Message: 'api/add-msg',
};
export default SortUrl;
