export const USERDATA = "USERDATA";
export const ALLUSERLIST = "ALLUSERLIST";
export const CHATLIST = "CHATLIST";
export const ALL_MESSAGE = "ALL_MESSAGE";
export const GROUPLIST = "GROUPLIST";
export const ALLADDEDUSERLIST = "ALLADDEDUSERLIST";
export const ALLPARTICIPIANTSLIST = "ALLPARTICIPIANTSLIST";
export const SAVEALLCHATMESSAGE = "SAVEALLCHATMESSAGE";