export const DOCTORRECORD = 'DOCTORRECORD';

export const DOCTORRECORDCONCATE = 'DOCTORRECORDCONCATE';

export const HOMEDATA = 'HOMEDATA';

export const BRAVOCARD = "BRAVOCARD";

export const FOLLOW = "FOLLOW";

export const CATEGORIES = "CATEGORIES";

export const NOTIFICATION = "NOTIFICATION";

export const ACCOUNTSETTING = "ACCOUNTSETTING";

export const USERDATA = "USERDATA";

export const DOCTORDETAILS = "DOCTORDETAILS";

export const DOCTORLIST = "DOCTORLIST";

export const PROFILEDATA = "PROFILEDATA";
