export const DOCTORRECORD = 'DOCTORRECORD';

export const SAVEFOLLOWDATA = 'SAVEFOLLOWDATA';

export const SAVEALLCOUNTRY = 'SAVEALLCOUNTRY';

export const SAVEALLSTATE = 'SAVEALLSTATE'; 

export const SAVEALLCITY = 'SAVEALLCITY';

export const LOGOUT = 'LOGOUT';

export const FEEDBACKUSERDATA = 'FEEDBACKUSERDATA';

export const MESSAGEANDCOMMENT = "MESSAGEANDCOMMENT";

export const DOCTORRECORDCONCATE = 'DOCTORRECORDCONCATE';

export const HOMEDATA = 'HOMEDATA';

export const BRAVOCARD = "BRAVOCARD";

export const CATEGORIES = "CATEGORIES";

export const NOTIFICATION = "NOTIFICATION";

export const ACCOUNTSETTING = "ACCOUNTSETTING";

export const USERDATA = "USERDATA";

export const DOCTORDETAILS = "DOCTORDETAILS";

export const DOCTORLIST = "DOCTORLIST";

export const SERVICESLIST = "SERVICESLIST";

export const USERGETDATA = "USERGETDATA";