import { StyleSheet, Dimensions } from 'react-native';
import { Fonts, Colors, Fontsize } from "@common";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
  // Doctor Cards
  addBravoCardBtn: {
    backgroundColor: Colors.appcolor,
    marginTop: 16,
    flex: 1,
    padding: 5,
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',

  },
  addBravoCardTxt: {
    color: Colors.white,
    textAlign: 'center',
    color: Colors.white,
    fontSize: Fontsize.small,
    lineHeight: 20,
    fontFamily: Fonts.ProximaNovaMedium,
    marginLeft: 4
  },
  doctorCardContainer: {
    borderRadius: 10,
    padding: 16,
    margin: 24,
    // flex: 1,
  },
  cardIconView: {
    height: 100,
    width: 100,
    backgroundColor: Colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  cardIcon: { height: 78, width: 78, borderRadius: 100, alignSelf: 'center' },
  DoctorCardShareView: {
    flexDirection: 'row',
    // justifyContent: 'space-around',
    marginTop: 24,
    marginBottom: 10
  },
  DoctorCardShareButton: {
    alignItems: 'center',
    flex: 1,
  },
  DoctorCardShareButtonIcon: {
    height: 30,
    width: 30,
  },
  //
  DoctorCardShareButtonText: {
    color: Colors.grey,
    fontSize: Fontsize.small,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
    marginTop: 10,
  },
  doctorDetails: { flex: 3, marginLeft: 24,justifyContent:"center", },
  doctorname: {
    color: Colors.black,
    fontSize: Fontsize.fontFifteen,
    lineHeight: 25,
    fontFamily: Fonts.ProximaNovaBold,
    marginBottom: 5,
    marginLeft: 5,
    alignContent:"center"
  },
  doctorProfile: {
    color: Colors.appcolor,
    fontSize: Fontsize.small,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
    marginLeft: 5,
  },
  ratingViewRed: {
    flexDirection: 'row',
    marginTop: 15,
    marginBottom: 10,
    alignItems: 'center',
  },
  ratingViewmain: {
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  ratingText: {
    color: Colors.black,
    fontSize: Fontsize.fontTwelve,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaMedium,
    marginLeft: 10,
    flex: 3,
  },
  clinicianReview: {
    color: Colors.darkGrey,
    fontSize: Fontsize.fontTwelve,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
  },
  yellowstarview: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchName: {
    fontSize: Fontsize.fontTwenty,
    lineHeight: 25,
    color: Colors.black,
  },
  searchkey: {
    backgroundColor: '#fff',
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: 10,
    paddingLeft: 20,
    elevation: 9,
    flex: 1,
    marginHorizontal: 15,
  },
  cardHospitalView: {},
  hospitalName: {
    color: Colors.black,
    fontSize: Fontsize.fontFifteen,
    fontFamily: Fonts.ProximaNovaSemibold,
    marginVertical: 5,
  },
  cardHospitalViewText: {
    color: Colors.lightGrey,
    fontSize: Fontsize.small,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
    flex: 1,
  },
  //
  cardHospitalViewButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  //
  cardPhotoButton: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: Colors.appcolor,
    borderRadius: 10,
    flex: 1,
    paddingVertical: 5,
  },
  videoButton: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderRadius: 10,
    flex: 1,
    paddingVertical: 5,
    marginHorizontal: 10,
  },
  cardPhotoImage: { height: 11.5, width: 13 },
  cardVideoText: {
    color: Colors.lightGrey,
  },
  cardPhotoText: {
    color: Colors.white,
    fontSize: Fontsize.small,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
    paddingLeft: 5,
  },
  cardVideoIcon: { height: 11.5, width: 13 },
  // Doctor Cards
  doctorCardContainer: {
    justifyContent: 'center',
    borderRadius: 10,
    flex: 1,
    padding: 15,
    margin: 10,
  },
  doctorCardIconVIew: {
    height: 100,
    width: 100,
    backgroundColor: Colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  // doctorCardIcon: {
  //   height: 100,
  //   width: 100,
  //   borderRadius: 100,
  //   alignSelf: 'center',
  // },
  DoctorCardShareView: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
  },
  DoctorCardShareButton: { alignItems: 'center', flex: 1 },
  DoctorCardShareButtonIcon: { height: 30, width: 30 },
  //
  DoctorCardShareButtonText: {
    color: Colors.grey,
    fontSize: Fontsize.small,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
    marginTop: 10,
  },
  doctorname: {
    color: Colors.black,
    fontSize: Fontsize.fontFifteen,
    lineHeight: 25,
    fontFamily: Fonts.ProximaNovaBold,
    marginVertical: 5,
  },
  doctorProfile: {
    color: Colors.appcolor,
    fontSize: Fontsize.small,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
  },
  ratingViewRed: {
    flexDirection: 'row',
    marginVertical: 10,
    alignItems: 'center',
  },
  ratingViewmain: {
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  star: { height: 9, width: 9 },
  ratingText: {
    color: Colors.black,
    fontSize: Fontsize.fontTwelve,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaMedium,
    marginLeft: 10,
    flex: 3,
  },
  clinicianReview: {
    color: Colors.darkGrey,
    fontSize: Fontsize.fontTwelve,
    lineHeight: 15,
    fontFamily: Fonts.ProximaNovaRegular,
  },
  yellowstarview: { flexDirection: 'row', alignItems: 'center' },
  searchName: {
    fontSize: Fontsize.fontTwenty,
    lineHeight: 25,
    color: Colors.black,
  },
  searchkey: {
    backgroundColor: '#fff',
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
    padding: 10,
    paddingLeft: 20,
    elevation: 9,
    flex: 1,
    marginHorizontal: 15,
  },

  //Modal

  centeredView1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.transparentBlack,
    opacity: 5,
  },
  centeredView2: {
    width: '92%',
    height: 360,
    borderRadius: 15,
    alignSelf: 'center',
    backgroundColor: Colors.white,
    elevation: 1,
  },
  headerView: {
    height: 50,
    backgroundColor: Colors.bottonColors,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  headerText: {
    color: Colors.white,
    fontSize: Fontsize.fontFifteen,
  },
  headerIcon: {
    height: 30,
    width: 30,
  },
});

export default styles;
