import { BackHandler } from 'react-native';

const Imagepath = {
    icon: require('../assect/icon/Logo.svg'),
    logo: require('../assect/icon/icon.png'),
    background: require('../assect/images/Welcome.png'),
    man: require('../assect/icon/man.png'),
    man1: require('../assect/icon/man1.png'),
    doctoricon: require('../assect/icon/doctoricon.png'),
    bg: require('../assect/images/bg.png'),
    google: require('../assect/icon/google.png'),
    user: require('../assect/icon/man.png'),
    lock: require('../assect/icon/lock.png'),
    email: require('../assect/icon/email.png'),
    eye: require('../assect/icon/eye.png'),
    eyehide: require('../assect/icon/eyehide.png'),
    twitter: require('../assect/icon/twitter.png'),
    fb: require('../assect/icon/fb.png'),
    yes: require('../assect/icon/yes.png'),
    check: require('../assect/icon/check.png'),
    business: require('../assect/icon/business.png'),
    doctorbg: require('../assect/images/doctorbg.png'),
    doctor: require('../assect/images/doctor.png'),
    homebg: require('../assect/images/homebg.png'),
    headerbg: require('../assect/images/headerbg.png'),
    homebg2: require('../assect/images/homebg2.png'),
    navmenu: require('../assect/icon/nav-menu.png'),
    searchbtn: require('../assect/icon/searchbtn.png'),
    profile: require('../assect/icon/profile.png'),
    Notification: require('../assect/icon/Notification.png'),
    Messageicon: require('../assect/icon/Messageicon.png'),
    Share: require('../assect/icon/Share.png'),
    Bravo: require('../assect/icon/Bravo.png'),
    commenticon: require('../assect/icon/commenticon.png'),
    Photo: require('../assect/icon/Photo.png'),
    Video: require('../assect/icon/Video.png'),
    doctors: require('../assect/icon/doctors.png'),
    redstar: require('../assect/icon/redstar.png'),
    yellowstar: require('../assect/icon/yellowstar.png'),
    Followicon: require('../assect/icon/Followicon.png'),
    doctor: require('../assect/images/doctor.png'),
    mess: require('../assect/icon/mess.png'),
    dot: require('../assect/icon/dot.png'),
    bluetick: require('../assect/icon/bluetick.png'),
    likeicon: require('../assect/icon/likeicon.png'),
    homeicon: require('../assect/icon/homeicon.png'),
    setting_icon: require('../assect/icon/setting-icon.png'),
    Notfication_icon: require('../assect/icon/Notfication-icon.png'),
    User_Icon: require('../assect/icon/User-icon.png'),
    bottom_plus: require('../assect/icon/plusIcon.png'),
    plus: require('../assect/icon/plus.png'),
    back: require('../assect/icon/back.png'),
    Videoicon: require('../assect/Video-icon.png'),
    Photos:require('../assect/Photo-icon.png'),
    alarm_clock:require('../assect/icon/alarm-clock.png'),
    Edit:require('../assect/icon/Edit.png'),
    camera:require('../assect/icon/camera.png'),
    hospital:require('../assect/icon/hospital.png'),
    down:require('../assect/icon/down.png'),
    send:require('../assect/icon/send.png'),
    follow:require('../assect/icon/follow.png'),
    videocall:require('../assect/icon/videocall.png'),
    voicecall:require('../assect/icon/voicecall.png'),
    Notification22:require('../assect/icon/Notification22.png'),
    Profilesetting:require('../assect/icon/Profilesetting.png'),
    Accountsetting:require('../assect/icon/Accountsetting.png'),
    help:require('../assect/icon/help.png'),
    privacy:require('../assect/icon/privacy.png'),
    Accountsetting:require('../assect/icon/Accountsetting.png'),
    Contact:require('../assect/icon/Contact.png'),
    i:require('../assect/icon/i.png'),
    homeicon:require('../assect/icon/homeicon.png'),
    setting:require('../assect/icon/setting.png'),
    Icons:require('../assect/icon/Icons.png'),
    doctoricon2:require('../assect/icon/doctoricon2.png'),
    crose:require('../assect/icon/crose.png'),
    addbravocard:require('../assect/icon/addbravocard.png'),
    write:require('../assect/icon/write.png'),
    whatshupicon:require('../assect/icon/whatshupicon.png'),
    facebookicon:require('../assect/icon/facebookicon.png'),
    twitericon:require('../assect/icon/twitericon.png'),
    instaicon:require('../assect/icon/instaicon.png'),
    mailicon:require('../assect/icon/mailicon.png'),
    attach:require('../assect/icon/attach.png'),
    // close:require('../assect/icon/close.png'),
    loading:require('../assect/icon/loading.png'),
    replyIcons:require('../assect/icon/replyIcons.png'),
    forwordIcon:require('../assect/icon/forwordIcon.png'),
    massege:require('../assect/icon/massege.png'),
    following:require('../assect/icon/following.png'),



  }

  export default Imagepath;